name: demo_app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.2.0
  flutter_svg: ^1.1.6
  equatable: ^2.0.5
  formz: ^0.4.1
  authentication:
    path: packages/authentication
  models:
    path: packages/models

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/image/sign_in_image.svg
    - assets/image/sign_in_image.png
    - assets/icons/facebook.svg
    - assets/icons/twitter.svg
    - assets/icons/linkedin.svg